require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Shop::CartsController do

  # This should return the minimal set of attributes required to create a valid
  # Shop::Cart. As you add validations to Shop::Cart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Shop::CartsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all shop_carts as @shop_carts" do
      cart = Shop::Cart.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shop_carts).should eq([cart])
    end
  end

  describe "GET show" do
    it "assigns the requested shop_cart as @shop_cart" do
      cart = Shop::Cart.create! valid_attributes
      get :show, {:id => cart.to_param}, valid_session
      assigns(:shop_cart).should eq(cart)
    end
  end

  describe "GET new" do
    it "assigns a new shop_cart as @shop_cart" do
      get :new, {}, valid_session
      assigns(:shop_cart).should be_a_new(Shop::Cart)
    end
  end

  describe "GET edit" do
    it "assigns the requested shop_cart as @shop_cart" do
      cart = Shop::Cart.create! valid_attributes
      get :edit, {:id => cart.to_param}, valid_session
      assigns(:shop_cart).should eq(cart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shop::Cart" do
        expect {
          post :create, {:shop_cart => valid_attributes}, valid_session
        }.to change(Shop::Cart, :count).by(1)
      end

      it "assigns a newly created shop_cart as @shop_cart" do
        post :create, {:shop_cart => valid_attributes}, valid_session
        assigns(:shop_cart).should be_a(Shop::Cart)
        assigns(:shop_cart).should be_persisted
      end

      it "redirects to the created shop_cart" do
        post :create, {:shop_cart => valid_attributes}, valid_session
        response.should redirect_to(Shop::Cart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shop_cart as @shop_cart" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shop::Cart.any_instance.stub(:save).and_return(false)
        post :create, {:shop_cart => {}}, valid_session
        assigns(:shop_cart).should be_a_new(Shop::Cart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shop::Cart.any_instance.stub(:save).and_return(false)
        post :create, {:shop_cart => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shop_cart" do
        cart = Shop::Cart.create! valid_attributes
        # Assuming there are no other shop_carts in the database, this
        # specifies that the Shop::Cart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shop::Cart.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cart.to_param, :shop_cart => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested shop_cart as @shop_cart" do
        cart = Shop::Cart.create! valid_attributes
        put :update, {:id => cart.to_param, :shop_cart => valid_attributes}, valid_session
        assigns(:shop_cart).should eq(cart)
      end

      it "redirects to the shop_cart" do
        cart = Shop::Cart.create! valid_attributes
        put :update, {:id => cart.to_param, :shop_cart => valid_attributes}, valid_session
        response.should redirect_to(cart)
      end
    end

    describe "with invalid params" do
      it "assigns the shop_cart as @shop_cart" do
        cart = Shop::Cart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shop::Cart.any_instance.stub(:save).and_return(false)
        put :update, {:id => cart.to_param, :shop_cart => {}}, valid_session
        assigns(:shop_cart).should eq(cart)
      end

      it "re-renders the 'edit' template" do
        cart = Shop::Cart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shop::Cart.any_instance.stub(:save).and_return(false)
        put :update, {:id => cart.to_param, :shop_cart => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shop_cart" do
      cart = Shop::Cart.create! valid_attributes
      expect {
        delete :destroy, {:id => cart.to_param}, valid_session
      }.to change(Shop::Cart, :count).by(-1)
    end

    it "redirects to the shop_carts list" do
      cart = Shop::Cart.create! valid_attributes
      delete :destroy, {:id => cart.to_param}, valid_session
      response.should redirect_to(shop_carts_url)
    end
  end

end
