# List of enabled modules
modules:
   - news
   - catalog
   - realty
   - shop
   - contact_us
   - demo

# News module parameters
news:
  name: "Новости"
realty:
  name: "Недвижимость"
shop:
  name: "Магазин" # use as title in an email message
  from_email: "support@example.com" # site support email
  bcc_email: "manager@example.com" # email for "blind copy"
  url: "http://example.com/shop" # base url for shop, use in an email message
contact_us:
  name: 'Связаться с нами'
demo:
  name: "Демо версия"

# # Modules parameters in fit environment
# development:
#   news:
#     name: "Новости"

# production:
#   news:
    # name: "Новости"
