# List of enabled modules
modules:
   - news
   - catalog
   - realty

# News module parameters
news:
  name: "Новости"
realty:
  name: "Недвижимость"
# # Modules parameters in fit environment
# development:
#   news:
#     name: "Новости"

# production:
#   news:
    # name: "Новости"