# List of enabled modules
modules:
   - news
   - catalog
   - realty
   - shop
   - demo
   - feedback

# News module parameters
news:
  name: "news.name"
realty:
  name: "realty.name"
shop:
  name: "shop.name" # use as title in an email message
  from_email: "support@example.com" # site support email
  bcc_email: "manager@example.com" # email for "blind copy"
  url: "http://example.com/shop" # base url for shop, use in an email message
demo:
  name: "demo.name"
  admin:
    login: "admin"
    password: "admin"
    email: "admin@devmen.ru"
feedback:
  name: 'feedback.name'
  contact_us:
    name: 'feedback.contact_us.name'
  about_us:
    name: 'feedback.about_us.name'
  contacts:
    name: 'feedback.contacts.name'
  reviews:
    name: 'feedback.reviews.name'
# # Modules parameters in fit environment
# development:
#   news:
#     name: "Новости"

# production:
#   news:
    # name: "Новости"
